print ("Rex Angelo Icasiano")
print ("Matuyatuya, Torrijos, Marinduque")
print ("December 03, 2001")
print ("Marinduque State College")
print ("BS Information Technology")
print ("2A")
print ("Playing Musical Instruments")
print ("Martial Arts")
print ("Cycling")
print ("Writing")
print ("Singing")
